name: Ubuntu reference generation

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
    main:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            solver: [8.0.3]
            tests_ref: [8.0.0]
            subdir: [short-tests, medium-tests, long-tests, valid-adq, valid-bind, valid-complex, valid-defaillance, valid-draft, valid-filter-outputs, valid-hydro, valid-hydroBind, valid-hydroPricing, valid-marginCost, valid-parallel, valid-thermal, valid-ts-gen-export]

        steps:

        - name: Get release
          id: get_release
          uses: bruceadams/get-release@v1.2.3

        - name: Checkout SimTest
          uses: actions/checkout@v2

        - name: Install Python requirements
          run: pip3 install -r requirements.txt

        - name: Download Antares_Simulator archive
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/download/v${{ matrix.solver }}/antares-${{ matrix.solver }}-Ubuntu-20.04.tar.gz -O antares_simulator.tar.gz
        - name: Unpack Antares_Simulator
          run: tar xvf antares_simulator.tar.gz

        - name: Remove archive for Antares_Simulator
          run: rm antares_simulator.tar.gz

        - name: Download Antares_Simulator_Tests
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests_NR/releases/download/$v{{ matrix.tests_ref}}/${{ matrix.subdir }}.zip -O input.zip

        - name: Unpack test studies
          run: unzip input.zip

        - name: Remove archive
          run: rm input.zip

        - name: Generate results
          run: python3 scripts/generate_reference.py ${{ matrix.subdir }} antares-${{ matrix.solver }}-Ubuntu-20.04/bin

        - name: tar.gz results
          run: tar zcf results.tar.gz ${{ matrix.subdir }}

        - name: Upload .tar.gz
          uses: actions/upload-release-asset@v1.0.2
          with:
            upload_url: ${{ steps.get_release.outputs.upload_url }}
            asset_path: results.tar.gz
            asset_name: ${{ matrix.subdir }}-${{ matrix.solver}}-${{ matrix.tests_ref }}.tar.gz
            asset_content_type: application/octet-stream
