name: Ubuntu reference generation

on:
  workflow_dispatch:
    inputs:
      as_base_version:
        description: 'Version of Antares_Simulator, excluding RC, beta, etc.'
        required: true
        default: '8.0.3'
      as_rc_beta:
        description : 'RC1, beta, etc.'
        required: false
        default: ''
      tags:
        description: 'Add a description here'

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout SimTest
          uses: actions/checkout@v2
        - name: Install Python requirements
          run: pip3 install -r requirements.txt
        - name: Download Antares_Simulator archive (RC, Beta, etc.)
          if: ${{ github.event.inputs.as_rc_beta }} != ''
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/download/v${{ github.event.inputs.as_base_version }}-${{ github.event.inputs.as_rc_beta }}/antares-${{ github.event.inputs.as_base_version}}-Ubuntu-20.04.tar.gz -O antares.tar.gz
        - name: Download Antares_Simulator archive
          if: ${{ github.event.inputs.as_rc_beta }} == ''
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/download/v${{ github.event.inputs.as_base_version }}/antares-${{ github.event.inputs.as_base_version}}-Ubuntu-20.04.tar.gz -O antares.tar.gz

        - name: Extract archive
          run: tar xvf antares.tar.gz
