name: Ubuntu reference generation

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
    main:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            solver: [8.0.3]
            tests_ref: [8.0.0]
            subdir: [short, medium, long]

        steps:

        - name: Get release
          id: get_release
          uses: bruceadams/get-release@v1.2.3

        - name: Checkout SimTest
          uses: actions/checkout@v2

        - name: Install Python requirements
          run: pip3 install -r requirements.txt

        - name: Download Antares_Simulator archive
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/download/v${{ matrix.solver }}/antares-${{ matrix.solver }}-Ubuntu-20.04.tar.gz -O antares_simulator.tar.gz
        - name: Unpack Antares_Simulator
          run: tar xvf antares_simulator.tar.gz

        - name: Remove archive for Antares_Simulator
          run: rm antares_simulator.tar.gz

        - name: Download Antares_Simulator_Tests
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests/archive/refs/tags/v${{ matrix.tests_ref }}.tar.gz -O antares_simulator_tests.tar.gz

        - name: Unpack Antares_Simulator_Tests
          run: tar xvf antares_simulator_tests.tar.gz

        - name: Remove archive Antares_Simulator_Tests
          run: rm antares_simulator_tests.tar.gz

        - name: Rename Antares_Simulator_Tests
          run: mv Antares_Simulator_Tests-* Antares_Simulator_Tests

        - name: Generate results
          run: python3 scripts/generate_reference.py Antares_Simulator_Tests/${{ matrix.subdir }}-tests antares-${{ matrix.solver }}-Ubuntu-20.04/bin

        - name: tar.xz results
          run: tar Jcf Antares_Simulator_Tests.tar.xz Antares_Simulator_Tests

        - name: Upload .tar.xz
          uses: actions/upload-release-asset@v1.0.2
          with:
            upload_url: ${{ steps.get_release.outputs.upload_url }}
            asset_path: Antares_Simulator_Tests.tar.xz
            asset_name: Antares_Simulator_Tests-${{ matrix.solver}}-${{ matrix.tests_ref }}.tar.xz
            asset_content_type: application/octet-stream
