name: Ubuntu reference generation

on:
  workflow_dispatch:
    inputs:
      as_base_version:
        description: 'Version of Antares_Simulator. RC, beta, unsupported for now.'
        required: true
        default: '8.0.3'
      as_test_version:
        description: 'Version for Antares_Simulator_Tests'
        required: true
        default: '8.0.0'
      tags:
        description: 'Add a description here'

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout SimTest
          uses: actions/checkout@v2

        - name: Install Python requirements
          run: pip3 install -r requirements.txt

        - name: Download Antares_Simulator archive
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/download/v${{ github.event.inputs.as_base_version }}/antares-${{ github.event.inputs.as_base_version }}-Ubuntu-20.04.tar.gz -O antares_simulator.tar.gz
        - name: Unpack Antares_Simulator
          run: tar xvf antares_simulator.tar.gz

        - name: Remove archive for Antares_Simulator
          run: rm antares_simulator.tar.gz

        - name: Download Antares_Simulator_Tests
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests/archive/refs/tags/v${{ github.event.inputs.as_test_version }}.tar.gz -O antares_simulator_tests.tar.gz

        - name: Unpack Antares_Simulator_Tests
          run: tar xvf antares_simulator_tests.tar.gz

        - name: Remove archive Antares_Simulator_Tests
          run: rm antares_simulator_tests.tar.gz

        - name: Rename Antares_Simulator_Tests
          run: mv Antares_Simulator_Tests-* Antares_Simulator_Tests

        - name: Generate results
          run: python3 scripts/generate_reference.py Antares_Simulator_Tests/short-tests antares-${{ github.event.inputs.as_base_version }}-Ubuntu-20.04/bin
