name: Ubuntu reference generation

on:
  workflow_dispatch:
    inputs:
      as_base_version:
        description: 'Version of Antares_Simulator. RC, beta, unsupported for now.'
        required: true
        default: '8.0.3'
      tags:
        description: 'Add a description here'

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout SimTest
          uses: actions/checkout@v2
        - name: Install Python requirements
          run: pip3 install -r requirements.txt
        - name: Download Antares_Simulator archive
          run: wget https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/download/v${{ github.event.inputs.as_base_version }}/antares-${{ github.event.inputs.as_base_version}}-Ubuntu-20.04.tar.gz -O antares.tar.gz
        - name: Extract archive
          run: tar xvf antares.tar.gz
